sed 's/chrI/chr1/'      $output/temp3.txt > $hotspots
sed 's/chrII/chr2/'     $output/temp3.txt > $hotspots
sed 's/chrIII/chr3/'    $output/temp3.txt > $hotspots
sed 's/chrIV/chr4/'     $output/temp3.txt > $hotspots
sed 's/chrV/chr5/'      $output/temp3.txt > $hotspots
sed 's/chrVI/chr6/'     $output/temp3.txt > $hotspots
sed 's/chrVII/chr7/'    $output/temp3.txt > $hotspots
sed 's/chrVIII/chr8/'   $output/temp3.txt > $hotspots
sed 's/chrIX/chr9/'     $output/temp3.txt > $hotspots
sed 's/chrX/chr10/'     $output/temp3.txt > $hotspots
sed 's/chrXI/chr11/'    $output/temp3.txt > $hotspots
sed 's/chrXII/chr12/'   $output/temp3.txt > $hotspots
sed 's/chrXIII/chr13/'  $output/temp3.txt > $hotspots
sed 's/chrXIV/chr14/'   $output/temp3.txt > $hotspots
sed 's/chrXV/chr15/'    $output/temp3.txt > $hotspots
sed 's/chrXVI/chr16/'   $output/temp3.txt > $hotspots
sed 's/chrXVII/chr17/'  $output/temp3.txt > $hotspots
sed 's/chrXVIII/chr18/' $output/temp3.txt > $hotspots
sed 's/chrXIX/chr19/'   $output/temp3.txt > $hotspots
sed 's/chrXX/chr20/'    $output/temp3.txt > $hotspots
sed 's/chrXXI/chr21/'   $output/temp3.txt > $hotspots
sed 's/chrXXII/chr22/'  $output/temp3.txt > $hotspots
